import { StyleSheet } from "react-native";

// ---------- Styles ----------
export const takerStyles = StyleSheet.create({
  container: {
    padding: 25,
    paddingTop: 40,
    paddingBottom: 120,
    backgroundColor: "#F9F9F9",
    alignItems: "stretch",
    minHeight: "100%",
    gap: 15,
  },
  greeting: {
    fontSize: 24,
  },
  howareyoutoday: {
    fontSize: 24,
    alignSelf: 'center',
    marginVertical: 25,
  },
  todayyouare: {
    fontSize: 20,
  },
  moodpastdays: {
    fontSize: 14,
  },
  header: {
    // marginTop: 80,
    fontSize: 20,
    fontWeight: "500",
    color: "#333",
    backgroundColor: "#e3f2fd",
    width: "60%",
    height: 50,
    // paddingHorizontal: 30,
    // paddingVertical: 15,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  moodBox: {
    backgroundColor: "#F4EEE0",
    minHeight: 121,
    borderRadius: 12,
    padding: 15,
  },
  moodRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 25,
  },
  moodCircle: {
    width: 22,
    height: 22,
    borderRadius: 20,
  },
  box: {
    backgroundColor: "#DBE8F5",
    borderRadius: 12,
    padding: 15,
  },
  ratingTitle: {
    fontSize: 20,
    // fontWeight: "500",
    marginBottom: 8,
  },
  starRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    flexWrap: "wrap"
  },
  star: {
    fontSize: 28,
    color: "#ccc",
    marginRight: 5,
  },
  starActive: {
    color: "#FFF176",
  },
  taskContext: {
    fontSize: 20,
    // fontWeight: "500",
    marginBottom: 10,
  },
  showerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  teskchoice: {
    flex: 1,
    height: 59,
    marginHorizontal: 5,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  teskchoiceText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 18,
  },
  taskHeader: {
    fontSize: 20,
    fontWeight: "600",
    marginVertical: 10,
  },
  taskBox: {
    backgroundColor: "#DFE9F5",
    borderRadius: 12,
    padding: 15,
  },
  taskCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    height: 67,
    padding: 15,
    paddingTop: 20,
    borderRadius: 8,
    marginBottom: 20,
  },
  taskTitle: {
    fontSize: 18,
    color: "#000",
  },
  taskTime: {
    fontSize: 18,
    color: "#000",
    fontWeight: "600",
  },
  sosContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 65,
    backgroundColor: "#5A5A5A",
    alignItems: "center",
    justifyContent: "center",
  },
  sosButton: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#F56C6C",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -80,
  },
  sosText: {
    color: "#fff",
    fontSize: 40,
    fontWeight: "bold",
  },

  // Mood screen
  moodContainer: {
    flex: 1,
    padding: 30,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  headerBox: {
    marginTop: 70,
    fontSize: 26,
    fontWeight: "700",
    color: "#333",
    backgroundColor: "#e3f2fd",
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 10,
    alignSelf: "center",
    textAlign: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  question: {
    marginTop: 25,
    marginBottom: 35,
    fontSize: 29,
    fontWeight: "500",
    color: "#444",
  },
  moodButton: {
    width: "90%",
    paddingVertical: 22,
    borderRadius: 12,
    alignItems: "center",
    marginVertical: 12,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    elevation: 3,
  },
  moodText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333",
  },
  backButton: {
    position: "absolute",
    left: "7%",
    top: "5%",
  },
});
